"""用户基本信息相关表

Revision ID: 31df14d6e5d3
Revises: 
Create Date: 2019-03-17 00:10:51.962887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31df14d6e5d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AddressArea',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('AAid', sa.String(length=8), nullable=False),
    sa.Column('AAname', sa.String(length=32), nullable=False),
    sa.Column('ACid', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('AAid')
    )
    op.create_table('AddressCity',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ACid', sa.String(length=8), nullable=False),
    sa.Column('ACname', sa.String(length=20), nullable=False),
    sa.Column('APid', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('ACid')
    )
    op.create_table('AddressProvince',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('APid', sa.String(length=8), nullable=False),
    sa.Column('APname', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('APid')
    )
    op.create_table('Admin',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=False),
    sa.Column('ADnum', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('ADname', sa.String(length=255), nullable=True),
    sa.Column('ADtelphone', sa.String(length=13), nullable=True),
    sa.Column('ADpassword', sa.Text(), nullable=False),
    sa.Column('ADfirstpwd', sa.Text(), nullable=True),
    sa.Column('ADfirstname', sa.Text(), nullable=True),
    sa.Column('ADheader', sa.Text(), nullable=True),
    sa.Column('ADlevel', sa.Integer(), nullable=True),
    sa.Column('ADstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ADid')
    )
    op.create_table('AdminNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ANid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=False),
    sa.Column('ANaction', sa.Text(), nullable=True),
    sa.Column('ANdoneid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ANid')
    )
    op.create_table('IDcheck',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IDCid', sa.String(length=64), nullable=False),
    sa.Column('IDCcode', sa.String(length=24), nullable=False),
    sa.Column('IDCname', sa.Text(), nullable=True),
    sa.Column('IDCresult', sa.Boolean(), nullable=True),
    sa.Column('IDCrealName', sa.Text(), nullable=True),
    sa.Column('IDCcardNo', sa.Text(), nullable=True),
    sa.Column('IDCaddrCode', sa.Text(), nullable=True),
    sa.Column('IDCbirth', sa.Text(), nullable=True),
    sa.Column('IDCsex', sa.Integer(), nullable=True),
    sa.Column('IDCcheckBit', sa.String(length=2), nullable=True),
    sa.Column('IDCaddr', sa.Text(), nullable=True),
    sa.Column('IDCerrorCode', sa.String(length=8), nullable=True),
    sa.Column('IDCreason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('IDCid')
    )
    op.create_table('User',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USname', sa.String(length=255), nullable=False),
    sa.Column('USrealname', sa.String(length=255), nullable=True),
    sa.Column('UStelphone', sa.String(length=13), nullable=True),
    sa.Column('USgender', sa.Integer(), nullable=True),
    sa.Column('USbirthday', sa.DateTime(), nullable=True),
    sa.Column('USidentification', sa.String(length=24), nullable=True),
    sa.Column('USheader', sa.Text(), nullable=True),
    sa.Column('USopenid1', sa.Text(), nullable=True),
    sa.Column('USopenid2', sa.Text(), nullable=True),
    sa.Column('USintegral', sa.Integer(), nullable=True),
    sa.Column('USlevel', sa.Integer(), nullable=True),
    sa.Column('USqrcode', sa.Text(), nullable=True),
    sa.Column('USpaycode', sa.Text(), nullable=True),
    sa.Column('UScontinuous', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('USid')
    )
    op.create_table('UserAddress',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UAid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UAname', sa.String(length=16), nullable=False),
    sa.Column('UAphone', sa.String(length=16), nullable=False),
    sa.Column('UAtext', sa.String(length=255), nullable=False),
    sa.Column('UApostalcode', sa.String(length=8), nullable=True),
    sa.Column('UAdefault', sa.Boolean(), nullable=True),
    sa.Column('AAid', sa.String(length=8), nullable=False),
    sa.Column('UAFrom', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UAid')
    )
    op.create_table('UserIntegral',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UIid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UIintegral', sa.Integer(), nullable=True),
    sa.Column('UIaction', sa.Integer(), nullable=True),
    sa.Column('UItype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UIid')
    )
    op.create_table('UserLoginTime',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ULTid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USTip', sa.String(length=64), nullable=True),
    sa.Column('ULtype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ULTid')
    )
    op.create_table('UserMetia',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UMid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UMurl', sa.Text(), nullable=True),
    sa.Column('UMtype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UMid')
    )
    op.create_table('UserSearchHistory',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('USHid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USHname', sa.String(length=64), nullable=False),
    sa.Column('USHtype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('USHid')
    )
    op.create_table('identifyingcode',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ICid', sa.String(length=64), nullable=False),
    sa.Column('ICtelphone', sa.String(length=14), nullable=False),
    sa.Column('ICcode', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('ICid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identifyingcode')
    op.drop_table('UserSearchHistory')
    op.drop_table('UserMetia')
    op.drop_table('UserLoginTime')
    op.drop_table('UserIntegral')
    op.drop_table('UserAddress')
    op.drop_table('User')
    op.drop_table('IDcheck')
    op.drop_table('AdminNotes')
    op.drop_table('Admin')
    op.drop_table('AddressProvince')
    op.drop_table('AddressCity')
    op.drop_table('AddressArea')
    # ### end Alembic commands ###
