"""add

Revision ID: 8982e54e0289
Revises: 80ac9e7351ce
Create Date: 2019-03-29 10:31:07.051069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8982e54e0289'
down_revision = '80ac9e7351ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Activity',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ACid', sa.Integer(), nullable=False),
    sa.Column('ACbackGround', sa.String(length=255), nullable=False),
    sa.Column('ACtopPic', sa.String(length=255), nullable=False),
    sa.Column('ACbutton', sa.String(length=16), nullable=True),
    sa.Column('ACtype', sa.Integer(), nullable=True),
    sa.Column('ACshow', sa.Boolean(), nullable=True),
    sa.Column('ACdesc', sa.Text(), nullable=True),
    sa.Column('ACname', sa.String(length=16), nullable=False),
    sa.Column('ACsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ACid')
    )
    op.create_index(op.f('ix_Activity_ACtype'), 'Activity', ['ACtype'], unique=True)
    op.add_column('GroupBuying', sa.Column('GBtimes', sa.Integer(), nullable=False))
    op.add_column('GroupbuyingUser', sa.Column('GUstatus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GroupbuyingUser', 'GUstatus')
    op.drop_column('GroupBuying', 'GBtimes')
    op.drop_index(op.f('ix_Activity_ACtype'), table_name='Activity')
    op.drop_table('Activity')
    # ### end Alembic commands ###
