"""'add'

Revision ID: bacb2617af3f
Revises: 31df14d6e5d3
Create Date: 2019-03-21 12:21:21.980532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bacb2617af3f'
down_revision = '31df14d6e5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BrandwithItems',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('BWIid', sa.String(length=64), nullable=False),
    sa.Column('ITid', sa.String(length=64), nullable=False),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('BWIid')
    )
    op.create_table('GroupBuying',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GBid', sa.String(length=64), nullable=False),
    sa.Column('GBstarttime', sa.DateTime(), nullable=False),
    sa.Column('GBendtime', sa.DateTime(), nullable=False),
    sa.Column('GBnum', sa.Text(), nullable=False),
    sa.Column('GBstatus', sa.Integer(), nullable=True),
    sa.Column('GBreason', sa.Text(), nullable=True),
    sa.Column('GBstart', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('GBid')
    )
    op.create_table('GroupbuyingItem',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GIid', sa.String(length=64), nullable=False),
    sa.Column('GBid', sa.String(length=64), nullable=True),
    sa.Column('GIstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('GIid')
    )
    op.create_table('GroupbuyingProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GPid', sa.String(length=64), nullable=False),
    sa.Column('GBid', sa.String(length=64), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=True),
    sa.Column('PRtitle', sa.String(length=255), nullable=False),
    sa.Column('GPprice', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('GPfreight', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('GPstocks', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('GPid')
    )
    op.create_table('GroupbuyingSku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GSid', sa.String(length=64), nullable=False),
    sa.Column('GPid', sa.String(length=64), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('SKUgpPrice', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUgpStock', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('GSid')
    )
    op.create_table('GroupbuyingUser',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GUid', sa.String(length=64), nullable=False),
    sa.Column('GIid', sa.String(length=64), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UShead', sa.Text(), nullable=True),
    sa.Column('USname', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('GUid')
    )
    op.create_table('Items',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ITid', sa.String(length=64), nullable=False),
    sa.Column('ITname', sa.String(length=16), nullable=False),
    sa.Column('ITsort', sa.Integer(), nullable=True),
    sa.Column('ITdesc', sa.String(length=255), nullable=True),
    sa.Column('ITtype', sa.Integer(), nullable=True),
    sa.Column('ITrecommend', sa.Boolean(), nullable=True),
    sa.Column('ITauthority', sa.Integer(), nullable=True),
    sa.Column('ITposition', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ITid')
    )
    op.create_index(op.f('ix_Items_ITtype'), 'Items', ['ITtype'], unique=False)
    op.create_table('ProductArea',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PAid', sa.String(length=64), nullable=False),
    sa.Column('PCid', sa.String(length=64), nullable=True),
    sa.Column('PAstatus', sa.Integer(), nullable=True),
    sa.Column('PAsort', sa.Integer(), nullable=True),
    sa.Column('PAimg', sa.Text(), nullable=True),
    sa.Column('PAdesc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('PAid')
    )
    op.create_table('ProductBrand',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.Column('PBlogo', sa.String(length=255), nullable=True),
    sa.Column('PBname', sa.Text(), nullable=True),
    sa.Column('PBdesc', sa.Text(), nullable=True),
    sa.Column('PBlinks', sa.String(length=255), nullable=True),
    sa.Column('PBbackgroud', sa.String(length=255), nullable=True),
    sa.Column('PBstatus', sa.Integer(), nullable=True),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('PBid')
    )
    op.create_table('ProductCategory',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PCid', sa.String(length=64), nullable=False),
    sa.Column('PCtype', sa.Integer(), nullable=False),
    sa.Column('PCname', sa.String(length=16), nullable=False),
    sa.Column('PCdesc', sa.String(length=125), nullable=True),
    sa.Column('ParentPCid', sa.String(length=64), nullable=True),
    sa.Column('PCsort', sa.Integer(), nullable=True),
    sa.Column('PCpic', sa.String(length=255), nullable=True),
    sa.Column('PCtopPic', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('PCid')
    )
    op.create_table('ProductImage',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PIid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PIpic', sa.String(length=255), nullable=False),
    sa.Column('PIsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('PIid')
    )
    op.create_table('ProductItems',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PIid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('ITid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('PIid')
    )
    op.create_table('ProductMonthSaleValue',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PMSVid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PMSVnum', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('PMSVid')
    )
    op.create_table('ProductScene',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PSid', sa.String(length=64), nullable=False),
    sa.Column('PSpic', sa.String(length=255), nullable=False),
    sa.Column('PSname', sa.String(length=16), nullable=False),
    sa.Column('PSsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('PSid')
    )
    op.create_table('ProductSku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('SKUpic', sa.String(length=255), nullable=False),
    sa.Column('SKUattriteDetail', sa.Text(), nullable=True),
    sa.Column('SKUprice', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUstock', sa.BIGINT(), nullable=True),
    sa.Column('SKUsn', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('SKUid')
    )
    op.create_table('ProductSkuValue',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PSKUid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PSKUvalue', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('PSKUid')
    )
    op.create_table('Products',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PRtitle', sa.String(length=255), nullable=False),
    sa.Column('PRprice', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('PRlinePrice', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('PRfreight', sa.Float(precision=10), nullable=True),
    sa.Column('PRstocks', sa.BIGINT(), nullable=True),
    sa.Column('PRsalesValue', sa.Integer(), nullable=True),
    sa.Column('PRsalesValueFake', sa.Integer(), nullable=True),
    sa.Column('PRstatus', sa.Integer(), nullable=True),
    sa.Column('PRmainpic', sa.String(length=255), nullable=True),
    sa.Column('PRattribute', sa.Text(), nullable=True),
    sa.Column('PCid', sa.String(length=64), nullable=True),
    sa.Column('PRdesc', mysql.LONGTEXT(), nullable=True),
    sa.Column('PRremarks', sa.String(length=255), nullable=True),
    sa.Column('PRfrom', sa.Integer(), nullable=True),
    sa.Column('PRdescription', sa.Text(), nullable=True),
    sa.Column('CreaterId', sa.String(length=64), nullable=False),
    sa.Column('PRaverageScore', sa.Float(precision=10), nullable=True),
    sa.Column('PRpurchaseNum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('PRid')
    )
    op.create_table('SceneItem',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SIid', sa.String(length=64), nullable=False),
    sa.Column('PSid', sa.String(length=64), nullable=False),
    sa.Column('ITid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('SIid')
    )
    op.create_table('SettlenmentApply',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SSAid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('SSid', sa.String(length=64), nullable=True),
    sa.Column('SSAabo', sa.Text(), nullable=True),
    sa.Column('SSArejectReason', sa.Text(), nullable=True),
    sa.Column('SSAstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('SSAid')
    )
    op.create_table('Supplizer',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.Column('SUloginPhone', sa.String(length=11), nullable=False),
    sa.Column('SUlinkPhone', sa.String(length=11), nullable=True),
    sa.Column('SUname', sa.String(length=32), nullable=True),
    sa.Column('SUlinkman', sa.String(length=16), nullable=False),
    sa.Column('SUaddress', sa.String(length=255), nullable=False),
    sa.Column('SUstatus', sa.Integer(), nullable=True),
    sa.Column('SUisseller', sa.Boolean(), nullable=True),
    sa.Column('SUbaseRate', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('SUbanksn', sa.String(length=32), nullable=True),
    sa.Column('SUbankname', sa.String(length=64), nullable=True),
    sa.Column('SUpassword', sa.String(length=255), nullable=True),
    sa.Column('SUheader', sa.String(length=255), nullable=True),
    sa.Column('SUcontract', sa.Text(), nullable=True),
    sa.Column('SUbusinessLicense', sa.Text(), nullable=True),
    sa.Column('SUregisteredFund', sa.String(length=255), nullable=True),
    sa.Column('SUmainCategory', sa.Text(), nullable=True),
    sa.Column('SUregisteredTime', sa.DateTime(), nullable=True),
    sa.Column('SUlegalPerson', sa.Text(), nullable=True),
    sa.Column('SUemail', sa.String(length=256), nullable=True),
    sa.Column('SUlegalPersonIDcardFront', sa.Text(), nullable=True),
    sa.Column('SUlegalPersonIDcardBack', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SUid')
    )
    op.create_index(op.f('ix_Supplizer_SUloginPhone'), 'Supplizer', ['SUloginPhone'], unique=True)
    op.create_table('SupplizerAccount',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SAid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('SAbankName', sa.Text(), nullable=True),
    sa.Column('SAbankDetail', sa.Text(), nullable=True),
    sa.Column('SAcardNo', sa.String(length=32), nullable=True),
    sa.Column('SAcardName', sa.Text(), nullable=True),
    sa.Column('SACompanyName', sa.Text(), nullable=True),
    sa.Column('SAICIDcode', sa.Text(), nullable=True),
    sa.Column('SAaddress', sa.Text(), nullable=True),
    sa.Column('SAbankAccount', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SAid')
    )
    op.create_table('SupplizerProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SPid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('SPid')
    )
    op.create_index(op.f('ix_SupplizerProduct_PRid'), 'SupplizerProduct', ['PRid'], unique=False)
    op.create_table('SupplizerSettlement',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SSid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('SSstatus', sa.Integer(), nullable=True),
    sa.Column('SSdealTime', sa.DateTime(), nullable=True),
    sa.Column('SSdealamount', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('SSid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SupplizerSettlement')
    op.drop_index(op.f('ix_SupplizerProduct_PRid'), table_name='SupplizerProduct')
    op.drop_table('SupplizerProduct')
    op.drop_table('SupplizerAccount')
    op.drop_index(op.f('ix_Supplizer_SUloginPhone'), table_name='Supplizer')
    op.drop_table('Supplizer')
    op.drop_table('SettlenmentApply')
    op.drop_table('SceneItem')
    op.drop_table('Products')
    op.drop_table('ProductSkuValue')
    op.drop_table('ProductSku')
    op.drop_table('ProductScene')
    op.drop_table('ProductMonthSaleValue')
    op.drop_table('ProductItems')
    op.drop_table('ProductImage')
    op.drop_table('ProductCategory')
    op.drop_table('ProductBrand')
    op.drop_table('ProductArea')
    op.drop_index(op.f('ix_Items_ITtype'), table_name='Items')
    op.drop_table('Items')
    op.drop_table('GroupbuyingUser')
    op.drop_table('GroupbuyingSku')
    op.drop_table('GroupbuyingProduct')
    op.drop_table('GroupbuyingItem')
    op.drop_table('GroupBuying')
    op.drop_table('BrandwithItems')
    # ### end Alembic commands ###
